theme: jekyll-theme-slate
markdown: kramdown
title: Linear Algebra Exercises
description: This is the documentation for my solutions to the Exercises of the course "Linear Algebra" at the Fernfachhochschule Schweiz (FFHS).

highlighter: rouge

navigation:
 - title: Introduction
   url: /index.html
   weight: 1
 - title: Exercise 1
   url: /exercises/exercise1.html
   weight: 1
 - title: Exercise 2
   url: /exercises/exercise2.html
   weight: 1
 - title: Exercise 3
   url: /exercises/exercise3.html
   weight: 1
